{
  "artifacts": [], 
  "command": "main", 
  "experiment": {
    "base_dir": "/SiamFC-TensorFlow", 
    "dependencies": [
      "numpy==1.16.4", 
      "sacred==0.7.4", 
      "tensorflow-gpu==1.13.1"
    ], 
    "mainfile": "train_siamese_model.py", 
    "name": "SiamFC-3s-color-scratch", 
    "repositories": [], 
    "sources": [
      [
        "configuration.py", 
        "_sources/configuration_bf82ad1de141c54a40e6c2a3ad548238.py"
      ], 
      [
        "siamese_model.py", 
        "_sources/siamese_model_f044d4174fe25afce5790e57e33311f4.py"
      ], 
      [
        "train_siamese_model.py", 
        "_sources/train_siamese_model_06bf58273bb49843ac8d31d0be4fb5cc.py"
      ], 
      [
        "utils/__init__.py", 
        "_sources/__init___d41d8cd98f00b204e9800998ecf8427e.py"
      ], 
      [
        "utils/misc_utils.py", 
        "_sources/misc_utils_72b59981b744ae2c09c7187de2e26f39.py"
      ]
    ]
  }, 
  "fail_trace": [
    "Traceback (most recent call last):\n", 
    "  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n", 
    "  File \"experiments/../train_siamese_model.py\", line 167, in main\n    _, loss, batch_loss = sess.run([train_op, model.total_loss, model.batch_loss])\n", 
    "  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 929, in run\n    run_metadata_ptr)\n", 
    "  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 1152, in _run\n    feed_dict_tensor, options, run_metadata)\n", 
    "  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 1328, in _do_run\n    run_metadata)\n", 
    "  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 1348, in _do_call\n    raise type(e)(node_def, op, message)\n", 
    "ResourceExhaustedError: OOM when allocating tensor with shape[8,8,57,57,57,57] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[node train/convolutional_alexnet_1/conv2/attention_augmentation2d_7/Tile (defined at /root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:2191) ]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n\n\t [[node train/Loss/total_loss (defined at experiments/../siamese_model.py:162) ]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n\n\nCaused by op u'train/convolutional_alexnet_1/conv2/attention_augmentation2d_7/Tile', defined at:\n  File \"experiments/SiamFC-3s-color-scratch.py\", line 29, in <module>\n    '--enforce_clean': False,\n  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/sacred/experiment.py\", line 209, in run\n    run()\n  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/sacred/run.py\", line 221, in __call__\n    self.result = self.main_function(*args)\n  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n  File \"experiments/../train_siamese_model.py\", line 105, in main\n    model.build()\n  File \"experiments/../siamese_model.py\", line 212, in build\n    self.build_image_embeddings(reuse=reuse)\n  File \"experiments/../siamese_model.py\", line 102, in build_image_embeddings\n    self.instance_embeds, _ = embedding_fn(self.instances, 0, reuse=True)\n  File \"experiments/../siamese_model.py\", line 99, in embedding_fn\n    return convolutional_alexnet(images, is_exemplar, reuse=reuse)\n  File \"experiments/../embeddings/convolutional_cbam2.py\", line 125, in convolutional_alexnet\n    b1 = augmented_conv2d(b1, 128, (5,5),(1,1))\n  File \"experiments/../embeddings/attn_augconv.py\", line 303, in augmented_conv2d\n    attn_out = AttentionAugmentation2D(depth_k, depth_v, num_heads, relative_encodings)(qkv_conv)\n  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 457, in __call__\n    output = self.call(inputs, **kwargs)\n  File \"experiments/../embeddings/attn_augconv.py\", line 158, in call\n    h_rel_logits, w_rel_logits = self.relative_logits(q)\n  File \"experiments/../embeddings/attn_augconv.py\", line 214, in relative_logits\n    transpose_mask=[0, 1, 2, 4, 3, 5])\n  File \"experiments/../embeddings/attn_augconv.py\", line 229, in relative_logits_1d\n    rel_logits = K.tile(rel_logits, [1, 1, 1, H, 1, 1])\n  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py\", line 2191, in tile\n    return tf.tile(x, n)\n  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py\", line 10105, in tile\n    \"Tile\", input=input, multiples=multiples, name=name)\n  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 788, in _apply_op_helper\n    op_def=op_def)\n  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py\", line 507, in new_func\n    return func(*args, **kwargs)\n  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 3300, in create_op\n    op_def=op_def)\n  File \"/root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 1801, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8,8,57,57,57,57] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[node train/convolutional_alexnet_1/conv2/attention_augmentation2d_7/Tile (defined at /root/anaconda3/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:2191) ]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n\n\t [[node train/Loss/total_loss (defined at experiments/../siamese_model.py:162) ]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n\n\n"
  ], 
  "heartbeat": "2019-06-23T15:29:21.566931", 
  "host": {
    "ENV": {}, 
    "cpu": "Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz", 
    "gpus": {
      "driver_version": "418.56", 
      "gpus": [
        {
          "model": "TITAN Xp", 
          "persistence_mode": false, 
          "total_memory": 12196
        }, 
        {
          "model": "TITAN Xp", 
          "persistence_mode": false, 
          "total_memory": 12196
        }, 
        {
          "model": "TITAN Xp", 
          "persistence_mode": false, 
          "total_memory": 12196
        }, 
        {
          "model": "TITAN Xp", 
          "persistence_mode": false, 
          "total_memory": 12196
        }, 
        {
          "model": "TITAN Xp", 
          "persistence_mode": false, 
          "total_memory": 12196
        }
      ]
    }, 
    "hostname": "df9015040597", 
    "os": [
      "Linux", 
      "Linux-4.15.0-48-generic-x86_64-with-debian-buster-sid"
    ], 
    "python_version": "2.7.16"
  }, 
  "meta": {
    "command": "main", 
    "options": {
      "--beat_interval": null, 
      "--capture": null, 
      "--comment": null, 
      "--debug": false, 
      "--enforce_clean": false, 
      "--file_storage": null, 
      "--force": true, 
      "--help": false, 
      "--loglevel": null, 
      "--mongo_db": null, 
      "--name": "SiamFC-3s-color-scratch", 
      "--pdb": false, 
      "--print_config": false, 
      "--priority": null, 
      "--queue": false, 
      "--sql": null, 
      "--tiny_db": null, 
      "--unobserved": false
    }
  }, 
  "resources": [], 
  "result": null, 
  "start_time": "2019-06-23T15:28:14.116819", 
  "status": "FAILED", 
  "stop_time": "2019-06-23T15:29:21.570937"
}